---
title: "Premiers pas avec R"
author: "Elias Bouacida"
date: last-modified
format: 
  html: default
  revealjs:
    output-file: slide-lecon1.html
    embed-resources: true
    scrollable: true
editor: source
institute: "Université Paris 8"
bibliography: "Bibliographie.bib"
lang: fr
execute: 
  echo: true
date-format: long
format-links: [revealjs]
---



# Introduction

## À vous de jouer !

Demandez à votre LLM préférez comment utiliser R et Rstudio.

Demandez lui de vous décrire l'interface.

## Premiers calculs

Dans votre classe, les notes sont de 12, 15, 13 et 8.

Calculez la moyenne.

Expliquez le code produit.

::: {.fragment}

```{r}
notes <- c(12, 15, 13, 8)

mean(notes)

print("La moyenne est de : ", mean(notes))
```

:::

# Notions

## Notions

Ecrivez dans votre journal ce que vous avez compris (pas ce que vous a donné le LLM) aux notions suivantes :

:::  {.incremental}

- Objet
- Assignation
- Types
- Fonctions
- Scripts

:::

::: {.notes}

Laissez du temps aux étudiants pour écrire et ensuite échangez sur ce qu'ils ont compris à ces différentes notions.
Diviser le temps entre les concepts.
Discuter avec les étudiants de ce qu'ils demandent aux LLM, en particulier, demander si quelqu'un a pensé à demander une explication avec des exemples.

:::

## Remarque

Vous pouvez demander des exemples !


