---
title: "Resultats étudiants"
author: "Elias"
format: html
execute: 
  cache: refresh
  warning: false
  echo: false
---

<!-- Exercice 1 de Yanis Medjnoun : il manque toujours une lettre. -->
<!-- Saada a rendu un exercice de Pedro, mais j'ai bien vu le bon exercice rendu. -->

```{r setup}
#| cache: false
source("TreatResults.R")
library(tidyverse)
```

```{r load}
dir <-  "Suivi/"
a <- list.files(dir, pattern = ".")
b <- lapply(a, function(x) paste(dir, x, sep=""))
c <- sapply(b, decode_results)

#tibble(names = a)# %>% 
#  knitr::kable()
```

```{r}
data <- NULL
failures <- c()
for (tab in c){
  if(is.data.frame(tab)){
    if(is.null(data)){
      data <- tab
    }
    else {
      tryCatch(data <- rbind(data, tab),
               error = function(e) cat("ERROR: ", conditionMessage(e), "\n"))
    }
  }
  else(
    failures <- c(failures, tab)
  )
}




```
Renommer les utilisateurs correctement

```{r}
data <- data %>% 
  mutate( user = str_to_title(user),
          user = case_match(
    user,
    "1" ~ "Alexia",
    "Youcef£" ~ "Youcef",
    "Chelda" ~ "Marie Chelda",
    "Yao T" ~ "Yao",
    "Zineb Salhi" ~ "Zineb",
    "Zinev Salhi" ~ "Zineb",
    "David B" ~ "David Bouboutou",
    "Niesh" ~ "Nivesh",
    "Cedric" ~ "Cédric",
    "Kininkong" ~ "Alex",
    "Sarah" ~ "Saada",
    .default = user
    )
    )
```

Maximum par leçon

```{r}
nquestions <- data %>%
  group_by(lesson_name) %>% 
  summarise(max_all = max(question_number))

knitr::kable(nquestions)
```


```{r}
summary <- data %>%
  group_by(user, lesson_name) %>%
  summarise(skip = mean(skipped, na.rm = TRUE), attempt = mean(attempt), max = (max(question_number))) %>% 
  inner_join(nquestions, by = "lesson_name") %>% 
  mutate(finished = (max/max_all), max = NULL, max_all = NULL, n = n())


  

knitr::kable(summary)
```

```{r}
summary %>%
  select(-c(skip, attempt)) %>% 
  pivot_wider(names_from = "lesson_name", values_from = "finished")  %>% 
  mutate(`Exercice 2` = as.integer(`Exercice 2`)) %>% 
  relocate(`Manip Simples` = `Première manipulations de R`, .after = n) %>%
  relocate(`Fonctions et Scripts`, .after = `Manip Simples`) %>%
  rename(`Exercice 1` = `Exercices de la première partie.`) %>% 
  relocate(`Analyse de données`, .after = `Exercice 1`) %>%
  relocate(`Exercice 2`, .after = `Analyse de données`) %>%
  relocate(`Créer des fonctions - partie 1`, .after = `Exercice 2`) %>% 
  relocate(`Créer des fonctions - partie 2`, .after = `Créer des fonctions - partie 1`) %>% 
  relocate(`Exercice 3`, .before = Logique) %>%
  knitr::kable()
```


```{r}
failures
```


## Exploring weird data




